### ISSUE TITLE
Host MDS has no NIDS

### ISSUE THREAD

**Issue by 5soniyar** [whamcloud/iml-common#58]
Hello,
         We are using iml-4.0.8.0 to monitor existing lustre file-system. While running detect file system it is throwing an error host mds has no NIDS. The lustre file system is working fine and we able to do lctl ping to all mds, oss and client nodes. Attached herewith the screen shot of error. Kindly help.
![iml_error](https://user-images.githubusercontent.com/38415216/47423212-1ca43f00-d7a2-11e8-95ff-e6aaff3087f0.PNG)

**Comment by johnsonw** [comment]
Hello @5soniyar,

It might be worth looking at the lustre network:
```
lnetctl net show
```

If you don't see anything that stands out with this information, I think the next step is to debug the agent node and see what commands are being issued so we can run them manually. See https://whamcloud.github.io/Support/docs/support/common-troubleshooting-tips.html to learn how to put an agent into debug mode.

Regards,

Will

**Comment by ldd91** [comment]
@5soniyar  i also met this problem,would  you mind to share how did you solve this problem?
